### ISSUE TITLE
Extend to plain json output format.

### ISSUE THREAD

**Issue by Mettbrot** [wcm-io/io.wcm.maven.plugins.i18n-maven-plugin#7]
Hi,

it would be nice to have an option to set the plugin to produce plain json output in the form
```
{
   "custom":{
      "message":[
         {
            "key1":"Value",
            "key2":"Value2"
         }
      ]
   },
   "message2":"value3"
}
```
or even
```
{
   "custom.message.key1":"Value",
   "custom.message.key2":"Value2",
   "message2":"value3"
}
```

Would this be possible?
Thanks

**Comment by stefanseifert** [comment]
would be possible - but what's the use case?

the plugin allows various input format, including similar ones in your example - and helps translating this in the more specific AEM-related i18n file formats. what would be the input format in your case?

it would be easy to add an option as in your second example (flat list of keys in JSON format) - it would just be a variation of the java properties output format we already provide.

**Comment by Mettbrot** [comment]
We want to use one file format for both backend and frontend. So we decided on properties files for backend and want to convert them to json in order to use them with [vuei18n](https://github.com/intlify/vue-i18n-next). Simple flat list of keys would be fine for that purpose.
How could we include such an option for the output file? Maybe something like an `<outputStandard>sling/simple/...</outputStandard>`?

**Comment by stefanseifert** [comment]
i've implemented a proposal in https://github.com/wcm-io/io.wcm.maven.plugins.i18n-maven-plugin/pull/9 - introducing a new output format "JSON_PROPERTIES". can you give it a try?
